// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFarm.Infrastructure.Persistence;

#nullable disable

namespace SmartFarm.Infrastructure.Migrations
{
    [DbContext(typeof(SmartFarmDbContext))]
    partial class SmartFarmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartFarm.Domain.Entities.Culture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParcelleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Variete")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateIntervention")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParcelleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Irrigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateIrrigation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Methode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParcelleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("VolumeEauLitres")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.ToTable("Irrigations");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.MesureCapteur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateMesure")
                        .HasColumnType("datetime2");

                    b.Property<double>("Humidite")
                        .HasColumnType("float");

                    b.Property<Guid>("ParcelleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.ToTable("Mesures");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Parcelle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SurfaceHectares")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Parcelles");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Plantation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CultureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatePlantation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRecoltePrevue")
                        .HasColumnType("datetime2");

                    b.Property<string>("Statut")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CultureId");

                    b.ToTable("Plantations");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Culture", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Parcelle", "Parcelle")
                        .WithMany("Cultures")
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Intervention", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Parcelle", "Parcelle")
                        .WithMany("Interventions")
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Irrigation", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Parcelle", "Parcelle")
                        .WithMany("Irrigations")
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.MesureCapteur", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Parcelle", "Parcelle")
                        .WithMany("Mesures")
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Plantation", b =>
                {
                    b.HasOne("SmartFarm.Domain.Entities.Culture", "Culture")
                        .WithMany("Plantations")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Culture");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Culture", b =>
                {
                    b.Navigation("Plantations");
                });

            modelBuilder.Entity("SmartFarm.Domain.Entities.Parcelle", b =>
                {
                    b.Navigation("Cultures");

                    b.Navigation("Interventions");

                    b.Navigation("Irrigations");

                    b.Navigation("Mesures");
                });
#pragma warning restore 612, 618
        }
    }
}
